
       name: LeetCode Sync
      
       on:
         workflow_dispatch:
         schedule:
           - cron: "0 8 * * *" #runs once a day

       permissions:
          contents: write
          pull-requests: write
          issues: write

       jobs:
         build:
           runs-on: ubuntu-latest
    
           steps:
             - name: Checkout
               uses: actions/checkout@v2

             - name: Set Git Config
               run: |
                 git config user.name "Kevin Liu"
                 git config user.email "null"

             - name: Sync
               uses: joshcai/leetcode-sync@v1.5
               with:
                 github-token: ${{ secrets.GITHUB_TOKEN }}
                 leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
                 leetcode-session: ${{ secrets.LEETCODE_SESSION }}
                 destination-folder: my-folder